In [1]:
# importar libreria
import numpy as np

In [3]:
lista = [1, 2, 3, 4, 5, 6]
print(lista)

[1, 2, 3, 4, 5, 6]


In [6]:
# convertir lista a array de una dimencion
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
type(arr)

numpy.ndarray

In [8]:
# convercion de matriz a array de dos dimenciones
matriz= [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# indexado de array de una dimencion
suma = arr[0] + arr[5]
suma

7

In [11]:
# indexado de array de dos dimenciones
# retorna la fila en la posicion indicada
res = matriz[0]
res

array([1, 2, 3])

In [16]:
# retorna valor de fila y columna especifico
matriz[0,2]

3

In [17]:
# slice
# selecciona un rango de valores
arr[0:3]

array([1, 2, 3])

In [18]:
# slice de principio a una posicion
arr[:3]

array([1, 2, 3])

In [19]:
# slice desde una posicion hasta el final
arr[3:]

array([4, 5, 6])

In [20]:
# slice con saltos
arr[::2]

array([1, 3, 5])

In [21]:
# los ultimos 3 valores
arr[-3:]

array([4, 5, 6])

In [22]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# slice de una matriz
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])