In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
# MUESTRA EL TIPO DE DATO DEL ARRAY
arr.dtype

dtype('int64')

In [10]:
# DEFINIR EL TIPO DE DATO
arr = np.array([1,2,3,4], dtype='float64')
arr

array([1., 2., 3., 4.])

In [11]:
arr.dtype

dtype('float64')

In [13]:
# CONVERTIR A OTRO TIPO DE DATO
arr = arr.astype(np.int64)
arr

array([1, 2, 3, 4])

In [15]:
# AL CONVERTIR A BOOL, SOLO LOS CEROS SON FALSE, EL RESTO TRUE
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [17]:
# CONVERTIR A STRING
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [19]:
# CONVERTIR DE STRING A INT8
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [37]:
# CONVERTIR DE STRING A INT8, esto genera un error
arr = np.array(['HOLA','1','2','3','4'])
arr = arr.astype(np.int8)
arr

ValueError: invalid literal for int() with base 10: 'HOLA'

In [38]:
# RANGO DE VALORES, CON SALTOS
arr = np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [39]:
# NUMERO DE VALORES EN UN INTERVALO
# 50 VALORES EN EL INTERVALO DE 1 Y 10
arr = np.linspace(1, 10, 50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])