In [1]:
import numpy as np

In [15]:
# VALOR ESCALAR, SIN DIMENCIONES
scalar = np.array(42)
print(scalar)
print('Dimencion: ', scalar.ndim)

42
Dimencion:  0


In [37]:
# DOS DIMENCIONES
vector = np.array([1, 2, 3])
print(vector)
print('Dimencion: ', vector.ndim)

[1 2 3]
Dimencion:  1


In [38]:
# TRES O MAS DIMENCIONES
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(tensor)
print('Dimencion: ', tensor.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Dimencion:  3


## AGREGAR O ELIMINAR DIMENCIONES

In [62]:
# AGREGAR DIMENCIONES AL MOMENTO DE CREAR ARRAYS
# SE ESTA CREANDO UN ARRAY CON 3 DIMENCIONES
vector = np.array([1, 2, 3], ndmin=3)
print(vector)
vector.ndim

[[[1 2 3]]]


3

In [64]:
# EXPANDE LA DIMENCION DE UN ARRAY
# EN ESTE CASO, EN FILAS (0 = FILA, 1 = COLUMNA)
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [66]:
# SQUEEZE ES UTIL PARA ELIMINAR O CONTRILAR LAS DIMENCIONES 
# SE COMPRIME AL NUMERO DE DIMENCIONES CORRECTO QUE SE ESTA USANDO
vector_2 = np.squeeze(vector)
print(vector_2)
vector_2.ndim

[1 2 3]


1

In [76]:
cinco_dim = np.array([[[[[10,11], [12,13]],[[14,15], [16,17]]], [[[18,19], [20,21]],[[22,23], [24,25]]]], [[[[26,27], [28,29]],[[30,31], [32,33]]], [[[34,35], [36,37]],[[38,39], [40,41]]]]])
print('Dimenciones: ', cinco_dim.ndim)
cinco_dim

Dimenciones:  5


array([[[[[10, 11],
          [12, 13]],

         [[14, 15],
          [16, 17]]],


        [[[18, 19],
          [20, 21]],

         [[22, 23],
          [24, 25]]]],



       [[[[26, 27],
          [28, 29]],

         [[30, 31],
          [32, 33]]],


        [[[34, 35],
          [36, 37]],

         [[38, 39],
          [40, 41]]]]])