In [1]:
import numpy as np

In [6]:
# CREAR SECUENCIA DE NUMERO
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# GENERAR CEROS
ceros = np.zeros(3)
ceros

array([0., 0., 0.])

In [14]:
# GENERAR CEROS ES UTIL PARA TENER ARRAYS CON DIMENCIONES YA CONOCIDAS
# PERO QUE NO SE SABE AUN SUS DATOS
ceros = np.zeros((3,3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# TAMBIEN SE PUEDE GENERAR ARRAYS DE SOLO UNOS
unos = np.ones((4,4))
unos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# CREA UNA CANTIDAD DEFINIDA DE NUEMROS EN UN RANGO
# 20 VALORES EQUIDISTANTES, ENTRE 0 Y 10
rango_distribuido = np.linspace(0, 10, 20)
rango_distribuido

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [22]:
# UTIL EN ALGEBRA LINEAL
# DIAGONAL DE SOLO UNOS
diagonal = np.eye(4)
diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [118]:
# GENERAR UN RANDOM DECIMAL
random = np.random.rand()
random

0.17142781324509082

In [119]:
# GENERA UN VECTOR CON ELEMENTOS RANDOM DECIMALES
arr = np.random.rand(5)
arr

array([0.25453838, 0.98938098, 0.77882138, 0.13267176, 0.82292123])

In [120]:
# GENERA UNA MATRIZ CON ELEMRNTOS RANDOM DECIMALES
matriz = np.random.rand(4,4)
matriz

array([[0.10782101, 0.22209647, 0.46813697, 0.97611851],
       [0.3637563 , 0.66607912, 0.03291788, 0.23128132],
       [0.23512316, 0.40263159, 0.14068439, 0.57516645],
       [0.65798546, 0.17364183, 0.41325675, 0.21443117]])

In [121]:
# GENERA UN RANDOM ENTRERO
random_entero = np.random.randint(0,20)
random_entero

10

In [122]:
# GENERA UNA MATRIZ CON ELEMENTOS RANDOM ENTEROS
matriz_random_entero = np.random.randint(0,20,(10,10))
matriz_random_entero

array([[12,  6,  7, 11, 15, 11,  9,  0,  8,  6],
       [ 2,  5,  8, 10,  6, 15, 13, 16,  4,  5],
       [11, 10, 15, 10,  2, 18,  0,  9, 10, 11],
       [18, 13,  9,  6,  3, 19, 10,  3,  0, 16],
       [ 0, 17,  9, 15,  3,  2, 19, 11,  9, 10],
       [ 4,  4, 19, 11, 13,  4, 11,  7, 10, 12],
       [19,  7, 14,  5,  4, 14, 16, 17, 11,  9],
       [10, 13,  1,  3,  7, 10, 19, 13, 13, 17],
       [ 9,  4, 16,  3,  5,  2, 13, 17,  2,  5],
       [11, 17, 10, 19, 19,  4, 11,  1, 15, 10]])