In [2]:
import numpy as np

## Arange

In [6]:
# CREAR SECUENCIA DE NUMERO
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Zeros y Ones

In [13]:
# GENERAR CEROS
ceros = np.zeros(3)
ceros

array([0., 0., 0.])

In [14]:
# GENERAR CEROS ES UTIL PARA TENER ARRAYS CON DIMENCIONES YA CONOCIDAS
# PERO QUE NO SE SABE AUN SUS DATOS
ceros = np.zeros((3,3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# TAMBIEN SE PUEDE GENERAR ARRAYS DE SOLO UNOS
unos = np.ones((4,4))
unos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Linspace

In [144]:
# CREA UNA CANTIDAD DEFINIDA DE NUEMROS EN UN RANGO
# 20 VALORES EQUIDISTANTES, ENTRE 0 Y 10
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [157]:
# CON endpoint=True, TOMA EN CUENTA EL ULTIMO VALOR
np.linspace(0, 10, 5, endpoint=True)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [158]:
# CON endpoint=False, NO TOMA EN CUENTA EL ULTIMO VALOR
np.linspace(0, 10, 5, endpoint=False)

array([0., 2., 4., 6., 8.])

## Eye

In [22]:
# UTIL EN ALGEBRA LINEAL
# DIAGONAL DE SOLO UNOS
diagonal = np.eye(4)
diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

In [118]:
# GENERAR UN RANDOM DECIMAL
random = np.random.rand()
random

0.17142781324509082

In [119]:
# GENERA UN VECTOR CON ELEMENTOS RANDOM DECIMALES
arr = np.random.rand(5)
arr

array([0.25453838, 0.98938098, 0.77882138, 0.13267176, 0.82292123])

In [120]:
# GENERA UNA MATRIZ CON ELEMRNTOS RANDOM DECIMALES
matriz = np.random.rand(4,4)
matriz

array([[0.10782101, 0.22209647, 0.46813697, 0.97611851],
       [0.3637563 , 0.66607912, 0.03291788, 0.23128132],
       [0.23512316, 0.40263159, 0.14068439, 0.57516645],
       [0.65798546, 0.17364183, 0.41325675, 0.21443117]])

In [47]:
# GENERA UN RANDOM ENTRERO DENTRO DE UN RANGO DETERMINADO
random_entero = np.random.randint(0,10)
random_entero

7

In [124]:
# GENERA UNA MATRIZ CON ELEMENTOS RANDOM ENTEROS, DENTRO DE UN RANGO DETERMINADO
matriz_random_entero = np.random.randint(0,10,(10,10))
matriz_random_entero

array([[0, 6, 4, 5, 9, 9, 5, 2, 5, 7],
       [8, 6, 9, 4, 1, 6, 1, 2, 0, 1],
       [2, 8, 2, 0, 1, 2, 5, 5, 0, 2],
       [2, 8, 2, 7, 9, 5, 5, 3, 5, 2],
       [8, 8, 6, 3, 9, 9, 4, 0, 9, 5],
       [9, 4, 8, 8, 6, 9, 2, 9, 9, 1],
       [8, 7, 4, 0, 1, 7, 2, 8, 9, 6],
       [2, 6, 0, 9, 4, 5, 4, 1, 0, 4],
       [4, 8, 2, 4, 0, 9, 2, 4, 9, 6],
       [3, 0, 7, 6, 2, 3, 1, 2, 2, 8]])

In [133]:
# ARRAY DON DIMENCIONES DETERMINADAS, CON SELECCION RANDOM DESDE UN SET DE DATOS (VECTOR)
np.random.choice([1,2,3,4,5,6,7,8,9,0], size=(4,3))

array([[1, 4, 0],
       [5, 0, 8],
       [4, 2, 0],
       [8, 4, 2]])

In [142]:
# CREAR UN ARRAY DE PUROS CEROS, COPIANDO LA DIMENCION DE OTRO ARRAY
# np.zeros_like()
ar = np.random.choice([1,2,3,4,5,6,7,8,9,0], size=(4,5))
np.zeros_like(ar)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## Full

In [128]:
# CREA UN ARRAY CON DIMENCIONES DETERMINADAS, Y CON EL ELEMENTO QUE SE DESEA
np.full((5,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])