In [1]:
import numpy as np

In [9]:
# GENERAMOS UN ARRAY
arr = np.random.randint(1,10, (3,2))
arr

array([[1, 8],
       [1, 7],
       [7, 9]])

## Shape

In [11]:
# SHAPE MUESTRA LAS DIMENCIONES DEL ARRAY
arr.shape

(3, 2)

## Reshape

In [13]:
# CAMBIA LA FORMA, REDIMENCIONA EL ARRAY
# LAS NUEVAS DIMENCIONES, TIENEN QUE SER CONMPATIBLES CON LAS ORIGINALES (MISMA CANTIDAD DE ELEMENTOS)
arr.reshape(1,6)

array([[1, 8, 1, 7, 7, 9]])

In [20]:
arr.reshape(2,3)

array([[1, 8, 1],
       [7, 7, 9]])

In [27]:
# RESHAPE DESDE EL CONSTRUCTOR DE NUMPY
np.reshape(arr, (2,3))

array([[1, 8, 1],
       [7, 7, 9]])

## Reshape con distintos metodos de orden

In [31]:
# ARRAY ORIGINAL
arr

array([[1, 8],
       [1, 7],
       [7, 9]])

In [33]:
# RESHAPE ORIGINAL, EN LENGUAJE C
# AVANZA POR FILAS DEL ARRAY ORIGINAL
np.reshape(arr, (2,3), 'C')

array([[1, 8, 1],
       [7, 7, 9]])

In [35]:
# REASHAPE SEGUN FORTRAM
# AVANZA POR COLUMNAS
np.reshape(arr, (2,3), 'F')

array([[1, 7, 7],
       [1, 8, 9]])

In [37]:
# EL SISTEMA ELIGE QUE USAR (C o FORTRAM)
# DEPENDE PARA CUAL ESTA OPTIMOZADO EL SISTEMA
np.reshape(arr, (2,3), 'A')

array([[1, 8, 1],
       [7, 7, 9]])

In [38]:
# ES RECOMENDABLE USAR LA FORMA DE 'C', ES LA BASE DE PYTHON
# NO DEJAR QUE EL SISTEMA ELIJA, UNO TIENE QUE TENER CLARO LA FORMA EN QUE SE ESTA APLICANDO EL RESHAPE