In [1]:
import numpy as np

In [3]:
arr = np.random.randint(0,20,10)
arr

array([ 3,  0,  1, 13,  6,  4,  9, 16, 18,  5])

In [5]:
matriz = arr.reshape(2,5)
matriz

array([[ 3,  0,  1, 13,  6],
       [ 4,  9, 16, 18,  5]])

## Max

In [13]:
# MAXIMO EN VECTOR
arr.max()

18

In [14]:
# MAXIMO EN MATRIZ
matriz.max()

18

In [15]:
# MAXIMO, POR FILAS
matriz.max(1)

array([13, 18])

In [16]:
# MAXIMO POR COLUMNA
matriz.max(0)

array([ 4,  9, 16, 18,  6])

## ArgMax

In [18]:
# INDICE DEL VALOR MAXIMO
arr.argmax()

8

In [21]:
# INDICE DEL VALOR MAYOR, POR COLUMNA
matriz.argmax(0)

array([1, 1, 1, 1, 0])

## Min

In [22]:
arr.min()

0

In [23]:
matriz.min()

0

In [24]:
matriz.min(0)

array([ 3,  0,  1, 13,  5])

## ArgMin

In [25]:
arr.argmin()

1

In [26]:
matriz.argmin(0)

array([0, 0, 0, 0, 1])

## PTP (pick yo pick)

In [27]:
arr

array([ 3,  0,  1, 13,  6,  4,  9, 16, 18,  5])

In [29]:
# DIFERENCIA DEL PICO MAS ALTO Y EL PICO MAS ALTO
arr.ptp()

18

In [31]:
matriz

array([[ 3,  0,  1, 13,  6],
       [ 4,  9, 16, 18,  5]])

In [35]:
# ptp EN UN EJE
matriz.ptp(0)

array([ 1,  9, 15,  5,  1])

## Percentil

In [45]:
arr.sort()
arr

array([ 0,  1,  3,  4,  5,  6,  9, 13, 16, 18])

In [41]:
# PERCENTILE MAS BAJO
np.percentile(arr, 0)

0.0

In [42]:
# PERCENTILE MEDIO
np.percentile(arr, 50)

5.5

In [43]:
# PERCENTILE MAS ALTO
np.percentile(arr, 100)

18.0

## Mediana

In [49]:
# MEDIANA
np.median(arr)

5.5

In [50]:
# MEDIANA POR EJE
np.median(matriz, 0)

array([ 3. ,  5. ,  8. , 10. , 11.5])

## DESVIACION ESTANDAR

In [55]:
np.std(arr)

5.953990258641679

## Varianza 

In [53]:
np.var(arr)

35.45

## Media

In [56]:
np.mean(arr)

7.5

In [58]:
# MEDIA POR EJE 0
np.mean(matriz,0)

array([ 3. ,  5. ,  8. , 10. , 11.5])

## Concatenar arrays

In [79]:
# SE CREAN DOS ARRAYS, DE 2 Y 1 DIMENCION
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [68]:
print('Dimenciones: ', a.ndim)
a

Dimenciones:  2


array([[1, 2],
       [3, 4]])

In [69]:
print('Dimenciones: ', b.ndim)
b

Dimenciones:  1


array([5, 6])

In [74]:
# ERROR, LAS DIMENCIONES DE AMBOS ARRAYS NO SON IGUALES
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [80]:
# SE EXPANDO EL ARRAY DE 1 A 2 DIMENCIONES
b = np.expand_dims(b, axis=0)
b

array([[5, 6]])

In [83]:
# CONCATENA DOS ARRAYS EN EL EJE 0
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
# AL CONCATENAR POR EL EJE 1, TAMBIEN SE DA UN ERRRO
# b NO ESTA EN LAS DIMENCIONES CORRECTAS
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [87]:
# SE SOLUCIONA TRANSPONIENDO EL ARRAY b
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])