In [21]:
import numpy as np

In [29]:
# CREAMOS UN ARRAY
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# SLICE DE UNA PARTE DEL ARRAY
pedaso_arr = arr[0:5]
pedaso_arr

array([1, 2, 3, 4, 5])

In [31]:
# MODIFICAMOS EL SLICE
pedaso_arr[:] = 3
pedaso_arr

array([3, 3, 3, 3, 3])

In [32]:
# EL ARRAY ORRIGINAL SE MODIFFICO
arr

array([ 3,  3,  3,  3,  3,  6,  7,  8,  9, 10])

In [43]:
# VOLVEMOS A CREAR EL ARRAY
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# SE TIENE QUE HACER UN COPPY PARA QUE LAS MODIFICACIONES NO ALTEREN LAS ARRAY ORIGINAL
arr_copy = arr.copy()
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
# HACEMOS SLICE
pedaso_arr = arr_copy[0:5]
pedaso_arr

array([1, 2, 3, 4, 5])

In [46]:
# MODIFICAMOS EL EL SLICE
pedaso_arr[:] = 3
pedaso_arr

array([3, 3, 3, 3, 3])

In [48]:
# ARR NO SUFRE CAMBIO
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])