In [29]:
import numpy as np

In [30]:
# CREAMOS ARRAY
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [31]:
# SE CREA UNA CONDICION, SE GENERA UN ARRAY DE BOOLEANOS
condicion = arr > 5
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [32]:
# FILTRAR EL ARRAY CON CON CONDICION BOOLEANA
arr[condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [33]:
# SE PUEDE APLICAR LA CONDICION DIRECTO ENTRE CORCHETES, COMO INDEX O SLICE
arr[arr>5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [34]:
# DOBLE CONDICION
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [35]:
# CODIFICAR LOS VALORES QUE CUMPLAN CON LA CONDICION
arr[arr>5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [36]:
# FILTRAR POR CONDICION DE IGUALDAD
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

In [37]:
# WHERE(CONDICION, VALOR SI SE CUMPLE LA CONDICION, VALOR SI NO SE CUMPLE LA FUNCION)
np.where(arr==99,1,0)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])