In [1]:
import numpy as np

In [32]:
# LISTA NORMAL
lista = [1, 2, 3]

In [33]:
# AL MULTIPLICAR PRO DOS, SE DUPLICAN LOS ELEMENTOS
lista * 2

[1, 2, 3, 1, 2, 3]

In [34]:
# CREAMOS UN ARRAY
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# MULTIPLICAMOS POR 2, LOS VALORES DEL ARRAY SE MULTIPLICAR POR 2
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
# TODOS LOS ARRAY IGUAL A 1/VALOR, SI HAY VALOR CERO, SALE UNA ALERTA, 
# NO SE DETIENE LA OPERACION
1 / arr

/tmp/ipykernel_172/2216946649.py:3: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [37]:
# CREO OTRO ARRAY
arr_2 = np.arange(0, 20, 2)
arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
# SUMA DE ARRAY,
# AL HACER OPERACIONES ARITMETICAS, LOS ARRAYS TIENEN QUE SER DE IGUAL DIMENCION
arr + arr_2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [39]:
# RESTA DE ARRAYS
arr - arr_2

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [40]:
# MULTIPLICAION DE ARRAYS
arr * arr_2

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162])

## Producto Punto

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# REDIMENCIONAMOS EL ARRAY, OPTENEMOS UNA MATRIZ
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
# REDIMENCIONAMMOS EL SEGUNDO ARRAY, A UNA DIMENION OPUESTA AL ARRAY 1
matriz_2 = arr_2.reshape(5,2)
matriz_2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [44]:
# PRODUCTO PUNTO
np.matmul(matriz, matriz_2)

array([[120, 140],
       [320, 390]])

In [45]:
# OTRA FORMA DE CALCULAR EL PRODUCTO PUNTO
matriz @ matriz_2

array([[120, 140],
       [320, 390]])